### ISSUE TITLE
survey form builder

### ISSUE THREAD

**Issue by PeteTomlin** [simonrolph/NatureCounts#15]
Attempted to create new block for recorder name using existing attribute. Block didn't appear when clicked create block, and no placeholder. Tried a few times, no luck. 

Now survey form has following error:  

![image](https://user-images.githubusercontent.com/75690789/101518229-8d564780-3979-11eb-8e7d-28e9e7dcf6b1.png)

https://record.wildsheffield.com/node/48

**Comment by johnvanbreda** [comment]
I've fixed the error.

The lack of attribute on the form is because this form is a "list of records at different places" form so you need to add a "Grid for entering lists species at different places" control in order to be able to enter species and see the occurrence attributes. When you add an occurrence attribute in this mode, a blue info message should appear where you added the control to explain that it's just a placeholder for the configuration and the actual control will appear inside a grid column.
