### ISSUE TITLE
Explore page formatting

### ISSUE THREAD

**Issue by PeteTomlin** [simonrolph/NatureCounts#23]
Explore page formatting seems to be broken, 

![image](https://user-images.githubusercontent.com/75690789/105860946-12f38c80-5fe6-11eb-87ea-de4a0f8f7e52.png)

**Comment by PeteTomlin** [comment]
Also, you used to be able to explore pictures.

**Comment by simonrolph** [comment]
It's because someone wrote an essay in the determiner box which has made the columns go wonky
![image](https://user-images.githubusercontent.com/17750766/105868538-2dc9ff00-5fee-11eb-88fd-8b80a5b1f2e5.png)

It is true that this new version of the explore page doesn't have a pictures tab. You can still explore by pictures on the old explore page but it's a lot slower: https://record.wildsheffield.com/explore/all-records-v1

**Comment by PeteTomlin** [comment]
How can that be avoided?

**Comment by simonrolph** [comment]
I have moved his comment into the comment box not the determiner box
