### ISSUE TITLE
add 'Project site' locations to the location autocomplete

### ISSUE THREAD

**Issue by simonrolph** [simonrolph/NatureCounts#78]

**Comment by simonrolph** [comment]
location type id: 17966

Should be a quick edit, but I believe it's a setting on a warehouse report?

**Comment by johnvanbreda** [comment]
For the default location autocomplete on the non-layout builder forms, the sites lookup for the location input should include your own sites plus any that are linked to the activity you are entering records for. But, I don't think we ever set up a sites editor page for your activities on Wild Sheffield so this is not possible. It wouldn't take long to copy from iRecord if that's what you are referring to.

For the layout builder forms, the location control can have a specific site type chosen (normally SRWT site I think), plus there is a tickbox to include sites related to the activity. So that would also benefit from the above.

If you can confirm I've got the right end of the stick before I make changes that would be good.

**Comment by simonrolph** [comment]
Thanks for checking, I think it's a more limited edit

For the enter a casual record / enter a list of records generic recording pages, currently when you start typing location names in the location input it brings up suggestions from SRWT site location type eg.
![image](https://user-images.githubusercontent.com/17750766/125255475-61c28380-e2f3-11eb-92b3-17bc07d90a0f.png)

Or on the other trust's sites it shows suggestions from Wildlife Trust Reserve location type:
![image](https://user-images.githubusercontent.com/17750766/125256024-ef05d800-e2f3-11eb-90d7-b992a4d0a57f.png)

I'm not quite sure how this autocomplete works - I'm not sure how the form and sites are linked. But we want it to also bring up suggestions from the 'Project site' location type 17966

Assumed it would be something in the projects/wildsheffield/my_sites_lookup report?

**Comment by johnvanbreda** [comment]
Ah - yes, forgot we had a custom report setup. I've added 17966 to the included site types. See https://github.com/BiologicalRecordsCentre/indicia-reports/blob/master/reports/projects/wildsheffield/my_sites_lookup.xml

**Comment by simonrolph** [comment]
Doesn't seem to work, have suggested an edit: https://github.com/BiologicalRecordsCentre/indicia-reports/pull/8

**Comment by johnvanbreda** [comment]
Thanks for the PR - I've applied this.
